/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.device.Camera'
    ],
    models: [
        'routeInfo',
        'UnitList',
        'MapLocations',
        'MiddleNorthModel',
        'HighNorthModel',
        'HighSouthModel',
        'MiddleSouthModel'
    ],
    stores: [
        'listRoutes',
        'UnitListStore',
        'MapStore',
        'MiddleNorthStore'
    ],
    views: [
        'RouteDetailsList',
        'FeedBackView',
        'Problem',
        'requestStop',
        'MyNavigationView',
        'UnitListView',
        'MyMap',
        'LoginForm',
        'RegisterForm',
        'MainView',
        'MiddleNorthView',
        'AboutUs',
        'EstTimeView',
        'ServiceTimes',
        'TrolleyAlerts'
    ],
    controllers: [
        'MyController',
        'UnitListController',
        'UserController',
        'MapController',
        'StopController',
        'AlertsController'
    ],
    name: 'PeopleMover',

    launch: function() {
        Ext.fly('appLoadingImage').destroy();
              Ext.fly('appLoadingIndicator').destroy();
        Ext.create('PeopleMover.view.MainView', {fullscreen: true});
    }

});
