/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        stores: [
            'listRoutes'
        ],

        refs: {
            list: 'main #myroutelist',
            listDetail: 'widget.DetailList',
            titleList: '#titleList',
            back: '#backButton'
        },

        control: {
            "list": {
                itemtap: 'onActivityListItemTap'
            }
        }
    },

    onActivityListItemTap: function(dataview, index, target, record, e, eOpts) {
        var sample = Ext.create('widget.DetailList');

        //Ext.getCmp('titleList').setTitle(MyApp.view.MyContainer.itemTpl);
        Ext.Viewport.remove(Ext.Viewport.getActiveItem(), true);
        Ext.Viewport.setActiveItem(sample);

        //            var sample = Ext.create('MyApp.view.RouteDetailsList');

    }

});