/*
 * File: app/controller/UnitListController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PeopleMover.controller.UnitListController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.util.DelayedTask'
    ],

    config: {
        models: [
            'UnitList'
        ],
        stores: [
            'UnitListStore'
        ],
        views: [
            'UnitListView'
        ]
    },

    launch: function() {
         var autocallFunction = function() {
                    var task = Ext.create('Ext.util.DelayedTask', function() {
                        var list = Ext.getCmp('unitlistview');
                        list.getStore().load();
                        list.refresh();
                        //console.log('callback!');
                        autocallFunction.call(this);
                    }, this);

                    task.delay(10000);
                };


                autocallFunction();
    }

});