/*
 * File: app/store/MapStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PeopleMover.store.MapStore', {
    extend: 'Ext.data.Store',

    requires: [
        'PeopleMover.model.MapLocations',
        'Ext.util.Sorter'
    ],

    config: {
        autoLoad: true,
        model: 'PeopleMover.model.MapLocations',
        storeId: 'MapStore'
    }
});