/*
 * File: app/view/Problem.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PeopleMover.view.Problem', {
    extend: 'Ext.form.Panel',
    alias: 'widget.problem',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Email',
        'Ext.field.TextArea',
        'Ext.Button'
    ],

    config: {
        fullscreen: true,
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        labelWrap: true,
                        name: 'nameBox',
                        required: true
                    },
                    {
                        xtype: 'emailfield',
                        label: 'Email',
                        labelWrap: true,
                        name: 'emailBox',
                        required: true,
                        placeHolder: 'email@example.com'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Report Issue',
                        labelWrap: true,
                        name: 'infoBox',
                        required: true
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'bProbSubmit',
                ui: 'confirm',
                text: 'Submit'
            }
        ]
    }

});