/*
 * File: app/view/RouteDetailsList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PeopleMover.view.RouteDetailsList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.DetailList',

    requires: [
        'Ext.XTemplate',
        'Ext.TitleBar',
        'Ext.Button',
        'Ext.Panel'
    ],

    config: {
        id: 'titeList',
        itemTpl: [
            '<div>List Item {string}</div>'
        ],
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                id: 'titleList',
                items: [
                    {
                        xtype: 'button',
                        docked: 'top',
                        itemId: 'mybutton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'panel',
                docked: 'top'
            }
        ],
        listeners: [
            {
                fn: 'onBackButtonTap',
                event: 'tap',
                order: 'before',
                delegate: '#mybutton'
            }
        ]
    },

    onBackButtonTap: function(button, e, eOpts) {
        var sample = Ext.create('widget.main');
        Ext.getCmp('myTabPanel').setActiveItem(0);
        Ext.Viewport.remove(Ext.Viewport.getActiveItem(), true);
            Ext.Viewport.setActiveItem(sample);

    }

});