/*
 * File: app/view/TrolleyAlerts.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PeopleMover.view.TrolleyAlerts', {
    extend: 'Ext.Container',
    alias: 'widget.trolleyalerts',

    requires: [
        'Ext.form.FieldSet',
        'Ext.Button',
        'Ext.field.TextArea'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                title: 'Trolley Alerts',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'bAlert',
                        ui: 'decline',
                        width: '100%',
                        text: 'ALERTS'
                    },
                    {
                        xtype: 'textareafield',
                        height: 259,
                        id: 'alertfield',
                        label: '',
                        labelAlign: 'top',
                        readOnly: true
                    }
                ]
            }
        ]
    }

});